name: survey_sdk
description: The Survey SDK is a toolkit that allows developers to integrate surveys into their Flutter applications
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
  
dependencies:
  collection: ^1.17.1
  datetime_picker_formfield: ^2.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.3
  http: ^1.1.0
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.5
  dart_code_metrics_presets: ^1.0.1
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test_cov_console: ^0.2.2
  very_good_analysis: ^5.0.0+1

flutter:
  generate: true

  assets:
    - test/assets/test_survey_data.json

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Medium.ttf
    - family: Karla
      fonts:
      - asset: fonts/Karla-Regular.ttf
      - asset: fonts/Karla-Bold.ttf